controller_manager:
  ros__parameters:
    update_rate: 100
    
    differential_drive_controller:
      type: diff_drive_controller/DiffDriveController
    
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

differential_drive_controller:
  ros__parameters:
    left_wheel_names: ['left_wheel_joint']
    right_wheel_names: ['right_wheel_joint']
    wheel_separation: 0.3
    wheel_radius: 0.05
    tf_frame_prefix: ''
    publish_limited_velocity: true
    
    # Set initial velocities to zero
    linear.x: 0.0
    angular.z: 0.0
    
    # Disable automatic movement
    enable_odom_tf: false
    publish_cmd: false

joint_state_broadcaster:
  ros__parameters:
    status_publisher_period: 1