  ---
  controller_manager:
    ros__parameters:
      update_rate: 50
      robot_description: "robot_description" # Uncomment if you donot pass it through the launch file

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster
        state_interfaces:
          - hardware_interface/JointStateInterface

      diff_drive_controller:
        ros__parameters:
          type: "diff_drive_controller/DiffDriveController"
          publish_rate: 50
          command_interface: velocity
          left_wheel_names: ["left_wheel_joint"]
          right_wheel_names: ["right_wheel_joint"]
          state_interfaces:
            - hardware_interface/JointStateInterface
          command_interfaces:
            - hardware_interface/PositionJointInterface
          wheel_separation: 0.3   # Adjust according to your robot's dimensions
          wheel_radius: 0.05    # Adjust according to your wheel radius
          odom_frame: "odom"
          base_frame: "base_link"
          cmd_vel_timeout: 0.5
          velocity_rolling_window_size: 10
          use_stamped_vel: false
